// Code generated by command: go run main.go -out ../scalar_select_amd64.s -stubs ../scalar_select_amd64_stub.go -pkg secp256k1. DO NOT EDIT.

//go:build amd64 && secp256k1_asm && !secp256k1_amd64_w5_bench

package secp256k1

// selectGeneratorW6 scans all 32 packed W6 points with a fixed SSE2 instruction sequence.
//
//go:noescape
func selectGeneratorW6(out *[8]uint64, table *[32][8]uint64, magnitude uint64)
