// Code generated by command: go run main.go -out ../internal/cpufeat/cpuid_amd64.s -stubs ../internal/cpufeat/cpuid_amd64.go -pkg cpufeat. DO NOT EDIT.

//go:build amd64 && secp256k1_asm

#include "textflag.h"

// func cpuid(leaf uint32, subleaf uint32) (eax uint32, ebx uint32, ecx uint32, edx uint32)
// Requires: CPUID
TEXT ·cpuid(SB), NOSPLIT, $0-24
	MOVL leaf+0(FP), AX
	MOVL subleaf+4(FP), CX
	CPUID
	MOVL AX, eax+8(FP)
	MOVL BX, ebx+12(FP)
	MOVL CX, ecx+16(FP)
	MOVL DX, edx+20(FP)
	RET
