// Code generated by command: go run main.go -out ../internal/cpufeat/cpuid_amd64.s -stubs ../internal/cpufeat/cpuid_amd64.go -pkg cpufeat. DO NOT EDIT.

//go:build amd64 && secp256k1_asm

package cpufeat

// cpuid executes CPUID for the requested leaf and subleaf.
//
//go:noescape
func cpuid(leaf uint32, subleaf uint32) (eax uint32, ebx uint32, ecx uint32, edx uint32)
