// Code generated by internal/addchain/generate.go. DO NOT EDIT.

package scalar

// Inv computes z = 1/x mod n. For x = 0, Inv returns 0.
func (z *Element) Inv(x *Element) *Element {
	out := scalarInv(*x)
	return z.Set(&out)
}

func scalarInv(x Element) Element {
	// Addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_101      = _10 + _11
	//	_111      = _10 + _101
	//	_1001     = _10 + _111
	//	_1011     = _10 + _1001
	//	_1101     = _10 + _1011
	//	_110100   = _1101 << 2
	//	_111111   = _1011 + _110100
	//	_1111110  = 2*_111111
	//	_1111111  = 1 + _1111110
	//	_11111110 = 2*_1111111
	//	_11111111 = 1 + _11111110
	//	i17       = _11111111 << 3
	//	i19       = i17 << 2
	//	i20       = 2*i19
	//	i21       = 2*i20
	//	i39       = (i21 << 7 + i20) << 9 + i21
	//	i73       = (i39 << 6 + i19) << 26 + i39
	//	x127      = (i73 << 4 + i17) << 60 + i73 + _1111111
	//	i154      = ((x127 << 5 + _1011) << 3 + _101) << 4
	//	i166      = ((_101 + i154) << 4 + _111) << 5 + _1101
	//	i181      = ((i166 << 2 + _11) << 5 + _111) << 6
	//	i193      = ((_1101 + i181) << 5 + _1011) << 4 + _1101
	//	i214      = ((i193 << 3 + 1) << 6 + _101) << 10
	//	i230      = ((_111 + i214) << 4 + _111) << 9 + _11111111
	//	i247      = ((i230 << 5 + _1001) << 6 + _1011) << 4
	//	i261      = ((_1101 + i247) << 5 + _11) << 6 + _1101
	//	i283      = ((i261 << 10 + _1101) << 4 + _1001) << 6
	//	return      (1 + i283) << 8 + _111111
	var z Element
	var (
		t0  Element
		t1  Element
		t2  Element
		t3  Element
		t4  Element
		t5  Element
		t6  Element
		t7  Element
		t8  Element
		t9  Element
		t10 Element
		t11 Element
		t12 Element
	)

	z.Square(&x)

	t2.Mul(&x, &z)

	t6.Mul(&z, &t2)

	t5.Mul(&z, &t6)

	t0.Mul(&z, &t5)

	t3.Mul(&z, &t0)

	t1.Mul(&z, &t3)

	z.Square(&t1)
	for s := 1; s < 2; s++ {
		z.Square(&z)
	}

	z.Mul(&t3, &z)

	t4.Square(&z)

	t7.Mul(&x, &t4)

	t4.Square(&t7)

	t4.Mul(&x, &t4)

	t9.Square(&t4)
	for s := 1; s < 3; s++ {
		t9.Square(&t9)
	}

	t10.Square(&t9)
	for s := 1; s < 2; s++ {
		t10.Square(&t10)
	}

	t11.Square(&t10)

	t8.Square(&t11)

	t12.Square(&t8)
	for s := 1; s < 7; s++ {
		t12.Square(&t12)
	}

	t11.Mul(&t11, &t12)

	for s := 0; s < 9; s++ {
		t11.Square(&t11)
	}

	t8.Mul(&t8, &t11)

	t11.Square(&t8)
	for s := 1; s < 6; s++ {
		t11.Square(&t11)
	}

	t10.Mul(&t10, &t11)

	for s := 0; s < 26; s++ {
		t10.Square(&t10)
	}

	t8.Mul(&t8, &t10)

	t10.Square(&t8)
	for s := 1; s < 4; s++ {
		t10.Square(&t10)
	}

	t9.Mul(&t9, &t10)

	for s := 0; s < 60; s++ {
		t9.Square(&t9)
	}

	t8.Mul(&t8, &t9)

	t7.Mul(&t7, &t8)

	for s := 0; s < 5; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t3, &t7)

	for s := 0; s < 3; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t6, &t7)

	for s := 0; s < 4; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t6, &t7)

	for s := 0; s < 4; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t5, &t7)

	for s := 0; s < 5; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t1, &t7)

	for s := 0; s < 2; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t2, &t7)

	for s := 0; s < 5; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t5, &t7)

	for s := 0; s < 6; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t1, &t7)

	for s := 0; s < 5; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t3, &t7)

	for s := 0; s < 4; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&t1, &t7)

	for s := 0; s < 3; s++ {
		t7.Square(&t7)
	}

	t7.Mul(&x, &t7)

	for s := 0; s < 6; s++ {
		t7.Square(&t7)
	}

	t6.Mul(&t6, &t7)

	for s := 0; s < 10; s++ {
		t6.Square(&t6)
	}

	t6.Mul(&t5, &t6)

	for s := 0; s < 4; s++ {
		t6.Square(&t6)
	}

	t5.Mul(&t5, &t6)

	for s := 0; s < 9; s++ {
		t5.Square(&t5)
	}

	t4.Mul(&t4, &t5)

	for s := 0; s < 5; s++ {
		t4.Square(&t4)
	}

	t4.Mul(&t0, &t4)

	for s := 0; s < 6; s++ {
		t4.Square(&t4)
	}

	t3.Mul(&t3, &t4)

	for s := 0; s < 4; s++ {
		t3.Square(&t3)
	}

	t3.Mul(&t1, &t3)

	for s := 0; s < 5; s++ {
		t3.Square(&t3)
	}

	t2.Mul(&t2, &t3)

	for s := 0; s < 6; s++ {
		t2.Square(&t2)
	}

	t2.Mul(&t1, &t2)

	for s := 0; s < 10; s++ {
		t2.Square(&t2)
	}

	t1.Mul(&t1, &t2)

	for s := 0; s < 4; s++ {
		t1.Square(&t1)
	}

	t0.Mul(&t0, &t1)

	for s := 0; s < 6; s++ {
		t0.Square(&t0)
	}

	t0.Mul(&x, &t0)

	for s := 0; s < 8; s++ {
		t0.Square(&t0)
	}

	z.Mul(&z, &t0)

	return z
}
