// Code generated by command: go run main.go -out ../internal/scalar/montgomery_amd64.s -stubs ../internal/scalar/montgomery_amd64_stub.go -pkg scalar. DO NOT EDIT.

//go:build amd64 && secp256k1_asm

package scalar

// invVartimeWordsADXAsm computes a scalar inverse for public canonical input words.
//
//go:noescape
func invVartimeWordsADXAsm(out *[4]uint64, x *[4]uint64)
