// Code generated by command: go run main.go -out ../internal/scalar/montgomery_amd64.s -stubs ../internal/scalar/montgomery_amd64_stub.go -pkg scalar. DO NOT EDIT.

//go:build amd64 && secp256k1_asm

#include "textflag.h"

// func invVartimeWordsADXAsm(out *[4]uint64, x *[4]uint64)
// Requires: ADX, BMI2, SSE2
TEXT ·invVartimeWordsADXAsm(SB), NOSPLIT, $0-16
	MOVQ x+8(FP), SI
	MOVQ (SI), R8
	MOVQ $0xbfd25e8cd0364141, R12
	MOVQ 8(SI), R9
	MOVQ $0xbaaedce6af48a03b, R13
	MOVQ 16(SI), R10
	MOVQ $0xfffffffffffffffe, R14
	MOVQ 24(SI), R11
	MOVQ $0xffffffffffffffff, R15
	MOVQ $0x0000000000000001, AX
	MOVQ AX, X0
	XORQ AX, AX
	MOVQ AX, X1
	MOVQ AX, X2
	MOVQ AX, X3
	MOVQ AX, X4
	MOVQ AX, X5
	MOVQ AX, X6
	MOVQ AX, X7
	MOVQ R8, AX
	ORQ  R9, AX
	ORQ  R10, AX
	ORQ  R11, AX
	JEQ  inv_return_zero

inv_loop:
	MOVQ R9, AX
	ORQ  R10, AX
	ORQ  R11, AX
	JNZ  inv_u_not_one
	CMPQ R8, $0x01
	JEQ  inv_return_x1

inv_u_not_one:
	MOVQ R13, AX
	ORQ  R14, AX
	ORQ  R15, AX
	JNZ  inv_v_not_one
	CMPQ R12, $0x01
	JEQ  inv_return_x2

inv_v_not_one:
inv_reduce_u:
	TESTQ $0x00000001, R8
	JNZ   inv_reduce_v
	TESTQ R8, R8
	JEQ   inv_u_shift_64
	BSFQ  R8, CX
	MOVQ  $0x0000000000000040, SI
	SUBQ  CX, SI
	SHRXQ CX, R8, AX
	SHLXQ SI, R9, BX
	ORQ   BX, AX
	MOVQ  AX, R8
	SHRXQ CX, R9, AX
	SHLXQ SI, R10, BX
	ORQ   BX, AX
	MOVQ  AX, R9
	SHRXQ CX, R10, AX
	SHLXQ SI, R11, BX
	ORQ   BX, AX
	MOVQ  AX, R10
	SHRXQ CX, R11, AX
	MOVQ  AX, R11
	JMP   inv_u_half

inv_u_shift_64:
	MOVQ R9, R8
	MOVQ R10, R9
	MOVQ R11, R10
	XORQ R11, R11
	MOVQ $0x0000000000000040, CX

inv_u_half:
	MOVQ  X0, DX
	MOVQ  $0x4b0dff665588b13f, AX
	IMULQ AX, DX
	CMPQ  CX, $0x40
	JEQ   inv_u_q_ready
	MOVQ  $0x0000000000000001, AX
	SHLXQ CX, AX, AX
	DECQ  AX
	ANDQ  AX, DX

inv_u_q_ready:
	MOVQ  CX, X13
	XORQ  SI, SI
	MOVQ  $0xbfd25e8cd0364141, CX
	MULXQ CX, AX, DI
	ADCXQ SI, AX
	MOVQ  X0, CX
	ADOXQ CX, AX
	MOVQ  AX, X8
	MOVQ  $0xbaaedce6af48a03b, CX
	MULXQ CX, AX, BX
	ADCXQ DI, AX
	MOVQ  X1, CX
	ADOXQ CX, AX
	MOVQ  AX, X9
	MOVQ  $0xfffffffffffffffe, CX
	MULXQ CX, AX, DI
	ADCXQ BX, AX
	MOVQ  X2, CX
	ADOXQ CX, AX
	MOVQ  AX, X10
	MOVQ  $0xffffffffffffffff, CX
	MULXQ CX, AX, BX
	ADCXQ DI, AX
	MOVQ  X3, CX
	ADOXQ CX, AX
	MOVQ  AX, X11
	ADCXQ SI, BX
	ADOXQ SI, BX
	MOVQ  BX, X12
	MOVQ  X13, CX
	CMPQ  CX, $0x40
	JEQ   inv_u_half_64
	MOVQ  $0x0000000000000040, SI
	SUBQ  CX, SI
	MOVQ  X8, AX
	MOVQ  X9, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X0
	MOVQ  X9, AX
	MOVQ  X10, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X1
	MOVQ  X10, AX
	MOVQ  X11, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X2
	MOVQ  X11, AX
	MOVQ  X12, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X3
	JMP   inv_u_half_done

inv_u_half_64:
	MOVQ X9, X0
	MOVQ X10, X1
	MOVQ X11, X2
	MOVQ X12, X3

inv_u_half_done:
	JMP inv_reduce_u

inv_reduce_v:
	TESTQ $0x00000001, R12
	JNZ   inv_reduced
	TESTQ R12, R12
	JEQ   inv_v_shift_64
	BSFQ  R12, CX
	MOVQ  $0x0000000000000040, SI
	SUBQ  CX, SI
	SHRXQ CX, R12, AX
	SHLXQ SI, R13, BX
	ORQ   BX, AX
	MOVQ  AX, R12
	SHRXQ CX, R13, AX
	SHLXQ SI, R14, BX
	ORQ   BX, AX
	MOVQ  AX, R13
	SHRXQ CX, R14, AX
	SHLXQ SI, R15, BX
	ORQ   BX, AX
	MOVQ  AX, R14
	SHRXQ CX, R15, AX
	MOVQ  AX, R15
	JMP   inv_v_half

inv_v_shift_64:
	MOVQ R13, R12
	MOVQ R14, R13
	MOVQ R15, R14
	XORQ R15, R15
	MOVQ $0x0000000000000040, CX

inv_v_half:
	MOVQ  X4, DX
	MOVQ  $0x4b0dff665588b13f, AX
	IMULQ AX, DX
	CMPQ  CX, $0x40
	JEQ   inv_v_q_ready
	MOVQ  $0x0000000000000001, AX
	SHLXQ CX, AX, AX
	DECQ  AX
	ANDQ  AX, DX

inv_v_q_ready:
	MOVQ  CX, X13
	XORQ  SI, SI
	MOVQ  $0xbfd25e8cd0364141, CX
	MULXQ CX, AX, DI
	ADCXQ SI, AX
	MOVQ  X4, CX
	ADOXQ CX, AX
	MOVQ  AX, X8
	MOVQ  $0xbaaedce6af48a03b, CX
	MULXQ CX, AX, BX
	ADCXQ DI, AX
	MOVQ  X5, CX
	ADOXQ CX, AX
	MOVQ  AX, X9
	MOVQ  $0xfffffffffffffffe, CX
	MULXQ CX, AX, DI
	ADCXQ BX, AX
	MOVQ  X6, CX
	ADOXQ CX, AX
	MOVQ  AX, X10
	MOVQ  $0xffffffffffffffff, CX
	MULXQ CX, AX, BX
	ADCXQ DI, AX
	MOVQ  X7, CX
	ADOXQ CX, AX
	MOVQ  AX, X11
	ADCXQ SI, BX
	ADOXQ SI, BX
	MOVQ  BX, X12
	MOVQ  X13, CX
	CMPQ  CX, $0x40
	JEQ   inv_v_half_64
	MOVQ  $0x0000000000000040, SI
	SUBQ  CX, SI
	MOVQ  X8, AX
	MOVQ  X9, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X4
	MOVQ  X9, AX
	MOVQ  X10, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X5
	MOVQ  X10, AX
	MOVQ  X11, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X6
	MOVQ  X11, AX
	MOVQ  X12, BX
	SHRXQ CX, AX, AX
	SHLXQ SI, BX, BX
	ORQ   BX, AX
	MOVQ  AX, X7
	JMP   inv_v_half_done

inv_v_half_64:
	MOVQ X9, X4
	MOVQ X10, X5
	MOVQ X11, X6
	MOVQ X12, X7

inv_v_half_done:
	JMP inv_reduce_v

inv_reduced:
	MOVQ R9, AX
	ORQ  R10, AX
	ORQ  R11, AX
	JNZ  inv_reduced_u_not_one
	CMPQ R8, $0x01
	JEQ  inv_return_x1

inv_reduced_u_not_one:
	MOVQ R13, AX
	ORQ  R14, AX
	ORQ  R15, AX
	JNZ  inv_reduced_v_not_one
	CMPQ R12, $0x01
	JEQ  inv_return_x2

inv_reduced_v_not_one:
	MOVQ R8, AX
	SUBQ R12, AX
	MOVQ R9, AX
	SBBQ R13, AX
	MOVQ R10, AX
	SBBQ R14, AX
	MOVQ R11, AX
	SBBQ R15, AX
	JCS  inv_v_greater
	SUBQ R12, R8
	SBBQ R13, R9
	SBBQ R14, R10
	SBBQ R15, R11
	MOVQ X0, AX
	MOVQ X4, BX
	SUBQ BX, AX
	MOVQ AX, X8
	MOVQ X1, AX
	MOVQ X5, BX
	SBBQ BX, AX
	MOVQ AX, X9
	MOVQ X2, AX
	MOVQ X6, BX
	SBBQ BX, AX
	MOVQ AX, X10
	MOVQ X3, AX
	MOVQ X7, BX
	SBBQ BX, AX
	MOVQ AX, X11
	JCC  inv_x1_sub_x2_no_borrow
	MOVQ X8, AX
	MOVQ $0xbfd25e8cd0364141, BX
	ADDQ BX, AX
	MOVQ AX, X0
	MOVQ X9, AX
	MOVQ $0xbaaedce6af48a03b, BX
	ADCQ BX, AX
	MOVQ AX, X1
	MOVQ X10, AX
	MOVQ $0xfffffffffffffffe, BX
	ADCQ BX, AX
	MOVQ AX, X2
	MOVQ X11, AX
	MOVQ $0xffffffffffffffff, BX
	ADCQ BX, AX
	MOVQ AX, X3
	JMP  inv_x1_sub_x2_done

inv_x1_sub_x2_no_borrow:
	MOVQ X8, X0
	MOVQ X9, X1
	MOVQ X10, X2
	MOVQ X11, X3

inv_x1_sub_x2_done:
	JMP inv_loop

inv_v_greater:
	SUBQ R8, R12
	SBBQ R9, R13
	SBBQ R10, R14
	SBBQ R11, R15
	MOVQ X4, AX
	MOVQ X0, BX
	SUBQ BX, AX
	MOVQ AX, X8
	MOVQ X5, AX
	MOVQ X1, BX
	SBBQ BX, AX
	MOVQ AX, X9
	MOVQ X6, AX
	MOVQ X2, BX
	SBBQ BX, AX
	MOVQ AX, X10
	MOVQ X7, AX
	MOVQ X3, BX
	SBBQ BX, AX
	MOVQ AX, X11
	JCC  inv_x2_sub_x1_no_borrow
	MOVQ X8, AX
	MOVQ $0xbfd25e8cd0364141, BX
	ADDQ BX, AX
	MOVQ AX, X4
	MOVQ X9, AX
	MOVQ $0xbaaedce6af48a03b, BX
	ADCQ BX, AX
	MOVQ AX, X5
	MOVQ X10, AX
	MOVQ $0xfffffffffffffffe, BX
	ADCQ BX, AX
	MOVQ AX, X6
	MOVQ X11, AX
	MOVQ $0xffffffffffffffff, BX
	ADCQ BX, AX
	MOVQ AX, X7
	JMP  inv_x2_sub_x1_done

inv_x2_sub_x1_no_borrow:
	MOVQ X8, X4
	MOVQ X9, X5
	MOVQ X10, X6
	MOVQ X11, X7

inv_x2_sub_x1_done:
	JMP inv_loop

inv_return_x1:
	MOVQ out+0(FP), SI
	MOVQ X0, (SI)
	MOVQ X1, 8(SI)
	MOVQ X2, 16(SI)
	MOVQ X3, 24(SI)
	RET

inv_return_x2:
	MOVQ out+0(FP), SI
	MOVQ X4, (SI)
	MOVQ X5, 8(SI)
	MOVQ X6, 16(SI)
	MOVQ X7, 24(SI)
	RET

inv_return_zero:
	MOVQ out+0(FP), SI
	XORQ AX, AX
	MOVQ AX, (SI)
	MOVQ AX, 8(SI)
	MOVQ AX, 16(SI)
	MOVQ AX, 24(SI)
	RET
