// Command genprecomp generates the secp256k1 base-point and verification tables.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"go/format"
	"math/big"
	"math/bits"
	"os"
)

const (
	baseWindowW5     = 5
	baseWindowsW5    = 52
	baseTableSizeW5  = 16
	baseWindowW6     = 6
	baseWindowsW6    = 43
	baseTableSizeW6  = 32
	generatorWindow  = 13
	generatorTableSz = 1 << (generatorWindow - 2)
	verifyCombWidth  = 7
	verifyCombRows   = (256 + verifyCombWidth - 1) / verifyCombWidth
	verifyCombSize   = 1 << verifyCombWidth
)

var (
	fieldPrime = mustBig("fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f")
	generator  = affinePoint{
		x: mustBig("79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"),
		y: mustBig("483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"),
	}
	endomorphismBeta = mustBig("7ae96a2b657c07106e64479eac3434e99cf0497512f58995c1396c28719501ee")
	montgomeryR      = new(big.Int).Mod(new(big.Int).Lsh(big.NewInt(1), 256), fieldPrime)
)

type affinePoint struct {
	x        *big.Int
	y        *big.Int
	infinity bool
}

func main() {
	w5 := buildFixedBaseTable(baseWindowW5, baseWindowsW5, baseTableSizeW5)
	w6 := buildFixedBaseTable(baseWindowW6, baseWindowsW6, baseTableSizeW6)
	wnaf := buildGeneratorOddTable()
	comb := buildGeneratorCombTable()
	endoX := make([][4]uint64, len(wnaf))
	for i := range wnaf {
		x := new(big.Int).Mul(wnaf[i].x, endomorphismBeta)
		x.Mod(x, fieldPrime)
		endoX[i] = montgomeryWords(x)
	}

	source, err := os.ReadFile("cmd/genprecomp/main.go")
	if err != nil {
		panic(err)
	}
	sourceHash := sha256.Sum256(source)

	var shared bytes.Buffer
	writeWNAFTable(&shared, wnaf)
	shared.WriteByte('\n')
	writeEndomorphismXTable(&shared, endoX)
	shared.WriteString("\nvar generatorWNAFTable, generatorEndoWNAFTable = loadGeneratorWNAFTables(&generatorWNAFTableWords, &generatorEndoWNAFXWords)\n")
	shared.WriteByte('\n')
	writeVerifyCombTable(&shared, comb[1:])
	shared.WriteString("\nvar generatorCombTable = loadGeneratorCombTable(&generatorCombTableWords)\n")
	writeGenerated("zz_precompute_tables.go", "", fmt.Sprintf("generator-wnaf-window=%d, verify-comb-width=%d", generatorWindow, verifyCombWidth), sourceHash, shared.Bytes())

	var w5Body bytes.Buffer
	writeFixedTable(&w5Body, "generatorAffineTableW5Words", w5)
	writeGenerated("zz_precompute_base_w5.go", "(!arm64 && !amd64) || !secp256k1_asm || (amd64 && secp256k1_amd64_w5_bench)", fmt.Sprintf("base-window=%d", baseWindowW5), sourceHash, w5Body.Bytes())

	var w6Body bytes.Buffer
	writeFixedTable(&w6Body, "generatorAffineTableW6Words", w6)
	writeGenerated("zz_precompute_base_w6_asm.go", "(arm64 && secp256k1_asm) || (amd64 && secp256k1_asm && !secp256k1_amd64_w5_bench)", fmt.Sprintf("base-window=%d", baseWindowW6), sourceHash, w6Body.Bytes())
}

func writeGenerated(path, buildTag, parameters string, sourceHash [32]byte, body []byte) {
	dataHash := sha256.Sum256(body)
	var output bytes.Buffer
	if buildTag != "" {
		fmt.Fprintf(&output, "//go:build %s\n\n", buildTag)
	}
	output.WriteString("// Code generated by cmd/genprecomp; DO NOT EDIT.\n")
	fmt.Fprintf(&output, "// Parameters: %s.\n", parameters)
	fmt.Fprintf(&output, "// Generator source SHA-256: %x.\n", sourceHash)
	fmt.Fprintf(&output, "// Table data SHA-256: %x.\n\n", dataHash)
	output.WriteString("package secp256k1\n\n")
	output.Write(body)
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		panic(err)
	}
}

func buildFixedBaseTable(window, windows, tableSize int) [][]affinePoint {
	table := make([][]affinePoint, windows)
	base := clonePoint(generator)
	for i := range table {
		table[i] = make([]affinePoint, tableSize)
		current := clonePoint(base)
		for j := range table[i] {
			table[i][j] = clonePoint(current)
			current = add(current, base)
		}
		for range window {
			base = double(base)
		}
	}
	return table
}

func buildGeneratorOddTable() []affinePoint {
	table := make([]affinePoint, generatorTableSz)
	step := double(generator)
	current := clonePoint(generator)
	for i := range table {
		table[i] = clonePoint(current)
		current = add(current, step)
	}
	return table
}

func buildGeneratorCombTable() []affinePoint {
	bases := make([]affinePoint, verifyCombWidth)
	bases[0] = clonePoint(generator)
	for i := 1; i < len(bases); i++ {
		bases[i] = clonePoint(bases[i-1])
		for range verifyCombRows {
			bases[i] = double(bases[i])
		}
	}

	table := make([]affinePoint, verifyCombSize)
	table[0] = affinePoint{infinity: true}
	for digit := 1; digit < len(table); digit++ {
		bit := bits.TrailingZeros(uint(digit))
		previous := digit & (digit - 1)
		table[digit] = add(table[previous], bases[bit])
	}
	return table
}

func add(p, q affinePoint) affinePoint {
	if p.infinity {
		return clonePoint(q)
	}
	if q.infinity {
		return clonePoint(p)
	}
	if p.x.Cmp(q.x) == 0 {
		ysum := mod(new(big.Int).Add(p.y, q.y))
		if ysum.Sign() == 0 {
			return affinePoint{infinity: true}
		}
		return double(p)
	}
	numerator := new(big.Int).Sub(q.y, p.y)
	denominator := mod(new(big.Int).Sub(q.x, p.x))
	denominator.ModInverse(denominator, fieldPrime)
	lambda := mod(numerator.Mul(numerator, denominator))
	x3 := mod(new(big.Int).Sub(new(big.Int).Sub(new(big.Int).Mul(lambda, lambda), p.x), q.x))
	y3 := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, new(big.Int).Sub(p.x, x3)), p.y))
	return affinePoint{x: x3, y: y3}
}

func double(p affinePoint) affinePoint {
	if p.infinity || p.y.Sign() == 0 {
		return affinePoint{infinity: true}
	}
	numerator := new(big.Int).Mul(p.x, p.x)
	numerator.Mul(numerator, big.NewInt(3))
	denominator := mod(new(big.Int).Lsh(new(big.Int).Set(p.y), 1))
	denominator.ModInverse(denominator, fieldPrime)
	lambda := mod(numerator.Mul(numerator, denominator))
	x3 := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, lambda), new(big.Int).Lsh(new(big.Int).Set(p.x), 1)))
	y3 := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, new(big.Int).Sub(p.x, x3)), p.y))
	return affinePoint{x: x3, y: y3}
}

func clonePoint(p affinePoint) affinePoint {
	if p.infinity {
		return affinePoint{infinity: true}
	}
	return affinePoint{x: new(big.Int).Set(p.x), y: new(big.Int).Set(p.y)}
}

func mod(x *big.Int) *big.Int {
	return x.Mod(x, fieldPrime)
}

func montgomeryWords(x *big.Int) [4]uint64 {
	montgomery := mod(new(big.Int).Mul(new(big.Int).Set(x), montgomeryR))
	var encoded [32]byte
	montgomery.FillBytes(encoded[:])
	return [4]uint64{
		binary.BigEndian.Uint64(encoded[24:32]),
		binary.BigEndian.Uint64(encoded[16:24]),
		binary.BigEndian.Uint64(encoded[8:16]),
		binary.BigEndian.Uint64(encoded[0:8]),
	}
}

func affineWords(p affinePoint) [8]uint64 {
	if p.infinity {
		panic("unexpected point at infinity")
	}
	x := montgomeryWords(p.x)
	y := montgomeryWords(p.y)
	return [8]uint64{x[0], x[1], x[2], x[3], y[0], y[1], y[2], y[3]}
}

func writeFixedTable(out *bytes.Buffer, name string, table [][]affinePoint) {
	fmt.Fprintf(out, "var %s = [%d][%d][8]uint64{\n", name, len(table), len(table[0]))
	for i := range table {
		out.WriteString("\t{\n")
		for j := range table[i] {
			writeWords8(out, affineWords(table[i][j]))
		}
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n")
}

func writeWNAFTable(out *bytes.Buffer, table []affinePoint) {
	fmt.Fprintf(out, "var generatorWNAFTableWords = [%d][8]uint64{\n", len(table))
	for _, p := range table {
		writeWords8(out, affineWords(p))
	}
	out.WriteString("}\n")
}

func writeEndomorphismXTable(out *bytes.Buffer, table [][4]uint64) {
	fmt.Fprintf(out, "var generatorEndoWNAFXWords = [%d][4]uint64{\n", len(table))
	for _, words := range table {
		fmt.Fprintf(out, "\t{0x%016x, 0x%016x, 0x%016x, 0x%016x},\n", words[0], words[1], words[2], words[3])
	}
	out.WriteString("}\n")
}

func writeVerifyCombTable(out *bytes.Buffer, table []affinePoint) {
	fmt.Fprintf(out, "var generatorCombTableWords = [%d][8]uint64{\n", len(table))
	for _, p := range table {
		writeWords8(out, affineWords(p))
	}
	out.WriteString("}\n")
}

func writeWords8(out *bytes.Buffer, words [8]uint64) {
	fmt.Fprintf(out, "\t\t{0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x},\n",
		words[0], words[1], words[2], words[3], words[4], words[5], words[6], words[7])
}

func mustBig(s string) *big.Int {
	x, ok := new(big.Int).SetString(s, 16)
	if !ok {
		panic("invalid integer constant")
	}
	return x
}
