// Command genprecomp generates the secp256k1 base-point and verification tables.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"go/format"
	"math/big"
	"os"
)

const (
	baseWindow       = 5
	baseWindows      = 52
	baseTableSize    = 16
	generatorWindow  = 13
	generatorTableSz = 1 << (generatorWindow - 2)
)

var (
	fieldPrime = mustBig("fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f")
	generator  = affinePoint{
		x: mustBig("79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"),
		y: mustBig("483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"),
	}
	endomorphismBeta = mustBig("7ae96a2b657c07106e64479eac3434e99cf0497512f58995c1396c28719501ee")
	montgomeryR      = new(big.Int).Mod(new(big.Int).Lsh(big.NewInt(1), 256), fieldPrime)
)

type affinePoint struct {
	x        *big.Int
	y        *big.Int
	infinity bool
}

func main() {
	w5 := buildFixedBaseTable()
	wnaf := buildGeneratorOddTable()
	endoX := make([][4]uint64, len(wnaf))
	for i := range wnaf {
		x := new(big.Int).Mul(wnaf[i].x, endomorphismBeta)
		x.Mod(x, fieldPrime)
		endoX[i] = montgomeryWords(x)
	}

	var body bytes.Buffer
	writeFixedTable(&body, w5)
	body.WriteByte('\n')
	writeWNAFTable(&body, wnaf)
	body.WriteByte('\n')
	writeEndomorphismXTable(&body, endoX)
	body.WriteString("\nvar generatorWNAFTable, generatorEndoWNAFTable = loadGeneratorWNAFTables(&generatorWNAFTableWords, &generatorEndoWNAFXWords)\n")

	hash := sha256.Sum256(body.Bytes())
	source, err := os.ReadFile("cmd/genprecomp/main.go")
	if err != nil {
		panic(err)
	}
	sourceHash := sha256.Sum256(source)
	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by cmd/genprecomp; DO NOT EDIT.\n")
	fmt.Fprintf(&output, "// Parameters: base-window=%d, generator-wnaf-window=%d.\n", baseWindow, generatorWindow)
	fmt.Fprintf(&output, "// Generator source SHA-256: %x.\n", sourceHash)
	fmt.Fprintf(&output, "// Table data SHA-256: %x.\n\n", hash)
	output.WriteString("package secp256k1\n\n")
	output.Write(body.Bytes())
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("zz_precompute_tables.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

func buildFixedBaseTable() [baseWindows][baseTableSize]affinePoint {
	var table [baseWindows][baseTableSize]affinePoint
	base := clonePoint(generator)
	for i := range table {
		current := clonePoint(base)
		for j := range table[i] {
			table[i][j] = clonePoint(current)
			current = add(current, base)
		}
		for range baseWindow {
			base = double(base)
		}
	}
	return table
}

func buildGeneratorOddTable() []affinePoint {
	table := make([]affinePoint, generatorTableSz)
	step := double(generator)
	current := clonePoint(generator)
	for i := range table {
		table[i] = clonePoint(current)
		current = add(current, step)
	}
	return table
}

func add(p, q affinePoint) affinePoint {
	if p.infinity {
		return clonePoint(q)
	}
	if q.infinity {
		return clonePoint(p)
	}
	if p.x.Cmp(q.x) == 0 {
		ysum := mod(new(big.Int).Add(p.y, q.y))
		if ysum.Sign() == 0 {
			return affinePoint{infinity: true}
		}
		return double(p)
	}
	numerator := new(big.Int).Sub(q.y, p.y)
	denominator := mod(new(big.Int).Sub(q.x, p.x))
	denominator.ModInverse(denominator, fieldPrime)
	lambda := mod(numerator.Mul(numerator, denominator))
	x3 := mod(new(big.Int).Sub(new(big.Int).Sub(new(big.Int).Mul(lambda, lambda), p.x), q.x))
	y3 := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, new(big.Int).Sub(p.x, x3)), p.y))
	return affinePoint{x: x3, y: y3}
}

func double(p affinePoint) affinePoint {
	if p.infinity || p.y.Sign() == 0 {
		return affinePoint{infinity: true}
	}
	numerator := new(big.Int).Mul(p.x, p.x)
	numerator.Mul(numerator, big.NewInt(3))
	denominator := mod(new(big.Int).Lsh(new(big.Int).Set(p.y), 1))
	denominator.ModInverse(denominator, fieldPrime)
	lambda := mod(numerator.Mul(numerator, denominator))
	x3 := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, lambda), new(big.Int).Lsh(new(big.Int).Set(p.x), 1)))
	y3 := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, new(big.Int).Sub(p.x, x3)), p.y))
	return affinePoint{x: x3, y: y3}
}

func clonePoint(p affinePoint) affinePoint {
	if p.infinity {
		return affinePoint{infinity: true}
	}
	return affinePoint{x: new(big.Int).Set(p.x), y: new(big.Int).Set(p.y)}
}

func mod(x *big.Int) *big.Int {
	return x.Mod(x, fieldPrime)
}

func montgomeryWords(x *big.Int) [4]uint64 {
	montgomery := mod(new(big.Int).Mul(new(big.Int).Set(x), montgomeryR))
	var encoded [32]byte
	montgomery.FillBytes(encoded[:])
	return [4]uint64{
		binary.BigEndian.Uint64(encoded[24:32]),
		binary.BigEndian.Uint64(encoded[16:24]),
		binary.BigEndian.Uint64(encoded[8:16]),
		binary.BigEndian.Uint64(encoded[0:8]),
	}
}

func affineWords(p affinePoint) [8]uint64 {
	if p.infinity {
		panic("unexpected point at infinity")
	}
	x := montgomeryWords(p.x)
	y := montgomeryWords(p.y)
	return [8]uint64{x[0], x[1], x[2], x[3], y[0], y[1], y[2], y[3]}
}

func writeFixedTable(out *bytes.Buffer, table [baseWindows][baseTableSize]affinePoint) {
	fmt.Fprintf(out, "var generatorAffineTableW5Words = [%d][%d][8]uint64{\n", baseWindows, baseTableSize)
	for i := range table {
		out.WriteString("\t{\n")
		for j := range table[i] {
			writeWords8(out, affineWords(table[i][j]))
		}
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n")
}

func writeWNAFTable(out *bytes.Buffer, table []affinePoint) {
	fmt.Fprintf(out, "var generatorWNAFTableWords = [%d][8]uint64{\n", len(table))
	for _, p := range table {
		writeWords8(out, affineWords(p))
	}
	out.WriteString("}\n")
}

func writeEndomorphismXTable(out *bytes.Buffer, table [][4]uint64) {
	fmt.Fprintf(out, "var generatorEndoWNAFXWords = [%d][4]uint64{\n", len(table))
	for _, words := range table {
		fmt.Fprintf(out, "\t{0x%016x, 0x%016x, 0x%016x, 0x%016x},\n", words[0], words[1], words[2], words[3])
	}
	out.WriteString("}\n")
}

func writeWords8(out *bytes.Buffer, words [8]uint64) {
	fmt.Fprintf(out, "\t\t{0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x, 0x%016x},\n",
		words[0], words[1], words[2], words[3], words[4], words[5], words[6], words[7])
}

func mustBig(s string) *big.Int {
	x, ok := new(big.Int).SetString(s, 16)
	if !ok {
		panic("invalid integer constant")
	}
	return x
}
