// Code generated by command: go run main.go -out ../internal/field/montgomery_amd64.s -stubs ../internal/field/montgomery_amd64_stub.go -pkg field. DO NOT EDIT.

//go:build amd64 && secp256k1_asm

package field

// mulMontgomeryADXAsm multiplies two canonical Montgomery field elements.
//
//go:noescape
func mulMontgomeryADXAsm(out *[4]uint64, x *[4]uint64, y *[4]uint64)

// squareMontgomeryADXAsm squares a canonical Montgomery field element.
//
//go:noescape
func squareMontgomeryADXAsm(out *[4]uint64, x *[4]uint64)

// squareMontgomeryNADXAsm performs a public number of repeated squarings.
//
//go:noescape
func squareMontgomeryNADXAsm(out *[4]uint64, x *[4]uint64, n uint64)

// mulByB3MontgomeryADXAsm multiplies a Montgomery field element by 21.
//
//go:noescape
func mulByB3MontgomeryADXAsm(out *[4]uint64, x *[4]uint64)
