// Code generated by command: go run main.go -out ../internal/field/montgomery_amd64.s -stubs ../internal/field/montgomery_amd64_stub.go -pkg field. DO NOT EDIT.

//go:build amd64 && secp256k1_asm

package field

// addMontgomeryADXAsm adds two canonical Montgomery field elements.
//
//go:noescape
func addMontgomeryADXAsm(out *[4]uint64, x *[4]uint64, y *[4]uint64)

// subMontgomeryADXAsm subtracts two canonical Montgomery field elements.
//
//go:noescape
func subMontgomeryADXAsm(out *[4]uint64, x *[4]uint64, y *[4]uint64)

// mulMontgomeryADXAsm multiplies two canonical Montgomery field elements.
//
//go:noescape
func mulMontgomeryADXAsm(out *[4]uint64, x *[4]uint64, y *[4]uint64)

// squareMontgomeryADXAsm squares a canonical Montgomery field element.
//
//go:noescape
func squareMontgomeryADXAsm(out *[4]uint64, x *[4]uint64)
