name: test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"
          check-latest: true
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - run: go build ./...
      - run: gofmt -d .
      - run: go vet ./...
      - run: go fix -diff ./...
      - run: go test -v -race -count=1 -cover ./...
